### PR TITLE
[WIP] Saliency Map Method in PyTorch

### PR DESCRIPTION
**Pull request by iArunava**

### CODE REVIEW

**Comment by iArunava** [comment]
@npapernot A quick question: it would be nice if you can clarify what this line is doing, as I understand its multiplying `H x W x C` the height, width and channels (ignoring the batch size). Am I right?
https://github.com/tensorflow/cleverhans/blob/f01d21deada2f835c759323ecc58981304054c05/cleverhans/attacks/saliency_map_method.py#L149

**Comment by npapernot** [comment]
That's correct, sorry for the delay in the response, I was on vacation

**Comment by iArunava** [comment]
Okay, I this is still under implementation. I will update this PR as soon as possible. Really feels great hearing from you, thanks.

**Comment by npapernot** [comment]
Thanks for working on this @iArunava, do you have any updates?

**Comment by npapernot** [comment]
Ping @iArunava ?

**Comment by jonasguan** [comment]
Closing this PR for now due to inactivity, since we're undergoing a major revamp. Happy to reopen if it's updated later.

**Pull request closed without merging**
