### PR TITLE
Update utils_keras.py

### PR DESCRIPTION
**Pull request by LaurensonR**
Add a VGG-type baseline CNN model

### CODE REVIEW

**Comment by LaurensonR** [comment]
> Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.

**Comment by LaurensonR** [comment]
@googlebot 
I signed it!

**Comment by LaurensonR** [comment]
@googlebot I signed it!

**Comment by npapernot** [comment]
Thank you for the PR. Unfortunately, to avoid duplicating code, we don't merge tutorials that change the model or dataset into the tutorials folder. If you'd like, you could add this into the examples folder but it will not be maintained.

**Comment by LaurensonR** [comment]
Hi, thanks for getting back to me.  I will take a look at adding the two tutorials to the examples folder.  In addition to the tutorials, the PR also included the addition of a new baseline model, VGG_model, which is a bit more resilient to adversarial attacks than the existing baseline CNN model.  Will that new model be merged into the master?  Thank you

**Comment by npapernot** [comment]
We're trying to move CleverHans to a more minimalistic library and focus on attacks + defenses rather than model definitions. It would be best if you could move the model definition to the example as well. Thank you!

**Comment by LaurensonR** [comment]
OK however I do feel that the new model is integrally related to the development of new attacks and defenses, as I found the existing model when used as a baseline was easy to beat in terms of resiliency to attacks while the new model is harder to beat and therefore provides a better baseline for the testing of attacks and defenses

**Comment by npapernot** [comment]
We're trying to move to a minimalist library so we won't be able to merge new models. Do you prefer to move the file or close the PR?

**Comment by LaurensonR** [comment]
I will move the file

Sent from Mail for Windows 10

**Comment by npapernot** [comment]
Gentle ping @LaurensonR : are you still working on this or do you want to close it?

**Comment by LaurensonR** [comment]
yes i hope to get back to it shortly.

**Comment by jonasguan** [comment]
Closing this for now since we're undergoing major updates, and this thread has been inactive for a while. Feel free to open a new PR if you're still working on it.

**Pull request closed without merging**
